version: '3.8'
services:
  frontend:
    build: 
      context: ./front_end
      dockerfile: ./Docker/Dockerfile.debug
    container_name: frontend-app
    volumes:
      - ./front_end:/app
      - /app/node_modules
    ports:
      - "5173:5173"
      - "9229:9229"
    command: npm run debug
  api:
    build:
      context: ./api
      dockerfile: ./Docker/Dockerfile.debug
    container_name: fastapi-app
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload